NumberOfColumns: 23
Columns: 
  deck_risk: category
  forecast_3_month: int
  forecast_6_month: int
  forecast_9_month: int
  in_transit_qty: int
  lead_time: int
  local_bo_qty: int
  min_bank: int
  national_inv: int
  oe_constraint: category
  perf_12_month_avg: float
  perf_6_month_avg: float
  pieces_past_due: int
  potential_issue: category
  ppap_risk: category
  rev_stop: category
  sales_1_month: int
  sales_3_month: int
  sales_6_month: int
  sales_9_month: int
  sku: int
  stop_auto_buy: category

target_column: went_on_backorder  

categorical_columns: 
  - deck_risk
  - ppap_risk

numerical_columns: 
  - national_inv
  - lead_time
  - in_transit_qty
  - forecast_3_month
  - forecast_6_month
  - forecast_9_month
  - sales_1_month
  - sales_3_month
  - sales_6_month
  - sales_9_month
  - min_bank
  - pieces_past_due
  - perf_6_month_avg
  - perf_12_month_avg
  - local_bo_qty